### SERVER
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

### SPRING
spring:
  application:
    name: wallet-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://root:toor@localhost:27017/admin}

### SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method

### LOGGING
logging:
  level:
    root: INFO
    com:
      example: TRACE
    org.springframework.data.mongodb: DEBUG

### ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### INFORMATION
info:
  app:
    name: "wallet-service"
    description: "Wallet service"
  author: ""
  java-version: ${java.version}